displayName: "Cloudflare Real-Client-IP Middleware"
type: middleware
import: github.com/danielbjornadal/traefik-cloudflare-plugin
iconPath: .assets/icon.png

summary: "Securely handles X-Forwarded-For and X-Real-IP when using Cloudflare (or other trusted proxies) in front of Traefik. Optional fetch of Cloudflare IP ranges, plus normalization for ipAllowList."

testData:
  disableDefault: false
  fetchCloudflareRanges: true
  cloudflareRangesHTTPTimeout: 5s
  trustedProxyRanges:
    - 193.53.88.88/29
  directRanges:
    - 0.0.0.0/0
    - ::/0
  header: "X-Forwarded-For"
